services:
  database: #sudo tar -czvpf archive.tar.gz /path/to/volume : sudo tar -xzvpf archive.tar.gz
    image: postgres:latest
    hostname: ${DB_HOSTNAME}
    networks:
      - talos-network
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes: 
      - ./volumes/database:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    command: -p ${DB_PORT}
  rabbitmq:
    image: rabbitmq:3.12.0-management
    hostname: ${RABBITMQ_HOSTNAME}
    networks:
      - talos-network
    ports:
      - ${RABBITMQ_SERVICE_PORT}:${RABBITMQ_SERVICE_PORT}
      - ${RABBITMQ_MANAGEMENT_PORT}:${RABBITMQ_MANAGEMENT_PORT}
    volumes:
        - ./volumes/rabbit:/var/lib/rabbitmq/
  rescan-producer:
    build:
      context: .
      dockerfile: docker-images/rescan-producer/Dockerfile
    networks:
      - talos-network
    env_file:
      - .env
networks:
  talos-network:
    driver: bridge